# Generated by Django 5.2 on 2025-07-05 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_video_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(default='Default Title', max_length=255),
            preserve_default=False,
        ),
    ]
